[build]
  base = "/"
  command = "npm run build"
  publish = "client/build"
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run start-server"
  targetPort = 3001
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
